[devshell]
name = "develpment-shell"
motd = """{106}Nix Development Shell{reset}

* Sloth is already installed

\n Use CTRL-D to leave the shell
"""

packages = [
    "gotools",
    "go-tools",
    "golangci-lint",
    "goreleaser",
    "moq"
]

startup.gomarkdoc.text = "go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest"
startup.aloe.text = "go install github.com/tfadeyi/aloe-cli@latest"
startup.sloth.text = "go install github.com/slok/sloth@latest"
#startup.slotalk.text = "go install github.com/tfadeyi/slotalk@latest"
