project_name: slotalk
before:
  hooks:
    - go mod tidy
builds:
  - id: "linux"
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X "internal/version.version={{.Version}}" -X "internal/version.commit={{.Commit}}" -X "internal/version.date={{.Date}}"
    binary: "{{ .ProjectName }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
  - id: "darwin"
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X "internal/version.version={{.Version}}" -X "internal/version.commit={{.Commit}}" -X "internal/version.date={{.Date}}"
    binary: "{{ .ProjectName }}"
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: linux
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    builds:
      - "linux"
  - id: darwin
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    builds:
      - "darwin"

kos:
  - working_dir: .
    id: "linux"
    build: "linux"
    base_image: gcr.io/distroless/base:nonroot
    labels:
      org.opencontainers.image.source: "https://github.com/tfadeyi/{{ .ProjectName }}"
      org.opencontainers.image.description: "Generate Sloth SLO/SLI definitions from source code."
      org.opencontainers.image.licenses: MIT
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.vendor: ""
      org.opencontainers.image.authors: "Oluwole Fadeyi"

    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
    tags:
      - latest
      - '{{.Tag}}'
    sbom: cyclonedx
    bare: true
    base_import_paths: true

checksum:
  name_template: "{{ .ProjectName }}-SHA256SUMS"
  algorithm: sha256
release:
  draft: true
changelog:
  use: github-native
  skip: false

signs:
  - cmd: cosign
    args:
      - "sign-blob"
      - "${artifact}"
      - "--output-signature=${signature}"
      - "--yes" # needed on cosign 2.0.0+
    artifacts: checksum
