name: Test and Lint
on:
  push:
    branches:
permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - uses: actions/checkout@v4
      - name: Install tools
        run: make install-ci-tools
      - name: Go Fmt
        run: diff -u <(echo -n) <(gofmt -d ./)
        shell: bash
      - name: Go Test
        run: make test
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest